# Utilisation de l'image TensorFlow officielle en tant que base
FROM python:3.10-slim
RUN apt-get update && apt-cache search libgl1-mesa-glx 
RUN apt-get install libgl1-mesa-glx
RUN pip install tensorflow==2.15.0
RUN pip install opencv-python
COPY test_compress.mp4 /app/test_compress.mp4
COPY animals.py /app/animals.py
WORKDIR /app
CMD ["python", "animals.py"]